---
- name: Install and configure Sanoid
  hosts: all
  become: true  # Run tasks as sudo

  tasks:
    - name: Install prerequisite software
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - debhelper
        - libcapture-tiny-perl
        - libconfig-inifiles-perl
        - pv
        - lzop
        - mbuffer
        - build-essential
        - git

    - name: Remove the cloned folder (if was created in former execution)
      ansible.builtin.file:
        path: /tmp/sanoid"
        state: absent

    # - name: Get list of packages to check if sanoid is installed
    #   ansible.builtin.package_facts:
    #     manager: auto
    #   register: package_facts

    - name: Get list of packages to check if sanoid is installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Build and install Sanoid Debian package (if not installed)
      shell: |
        cd /tmp
        git clone https://github.com/jimsalterjrs/sanoid.git
        cd sanoid
        git checkout $(git tag | grep "^v" | tail -n 1)
        ln -s packages/debian .
        dpkg-buildpackage -uc -us
        sudo apt install ../sanoid_*_all.deb
        rm /tmp/sanoid* -Rf
      args:
        executable: /bin/bash
      when: "'sanoid' not in ansible_facts.packages"

    - name: Copy Sanoid config's file
      copy:
        src: ../configs/sanoid.conf
        dest: /etc/sanoid/sanoid.conf
      become: yes

    - name: Enable and start the sanoid timer
      systemd:
        name: sanoid.timer
        enabled: yes
        state: started
